// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/camelcase/camelcase.d.ts
declare module "camelcase" {
	function camelcase(...args: string[]): string;
	namespace camelcase {}
	export = camelcase;
}
